#! /bin/bash
set -eu
[ $# -eq 1 ]
[ $1 == --libs ]
echo -lzepast   `libzepast_config --libs`   \
     -lmean     `libmean_config --libs`     \
     -lvariance `libvariance_config --libs` \
     -labsdev   `libabsdev_config --libs`

